# Generated by Django 4.1.2 on 2023-08-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosSubidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(blank=True, null=True, upload_to='./noche/static/noche/archivos/')),
                ('file2', models.FileField(blank=True, null=True, upload_to='./noche/static/noche/archivos/')),
                ('file3', models.FileField(blank=True, null=True, upload_to='./noche/static/noche/archivos/')),
                ('fecha_subida_file1', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_subida_file2', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_subida_file3', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
