# Generated by Django 4.1.2 on 2023-08-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noche', '0002_delete_archivossubidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaRotacionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv_checked', models.BooleanField(default=False)),
                ('bajado_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
