# Generated by Django 4.1.2 on 2023-08-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noche', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altarotacioncheck',
            name='bajado_checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='altarotacioncheck',
            name='lv_checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
