# Generated by Django 4.1.2 on 2023-08-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noche', '0004_alter_altarotacioncheck_bajado_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='altarotacioncheck',
            name='referencia',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
