# Generated by Django 4.1.2 on 2023-09-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noche', '0005_altarotacioncheck_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altarotacioncheck',
            name='referencia',
        ),
        migrations.AlterField(
            model_name='altarotacioncheck',
            name='bajado_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='altarotacioncheck',
            name='lv_checked',
            field=models.BooleanField(default=False),
        ),
    ]
