# Generated by Django 4.1.2 on 2023-08-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manana', '0008_alter_outs_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outs',
            name='motivo',
            field=models.CharField(choices=[('', 'Seleccione motivo'), ('Llenado', 'LLenado'), ('Picking', 'Picking'), ('PlanB', 'PlanB'), ('Guardia', 'Guardia'), ('L-L', 'L-L')], default='', max_length=10),
        ),
    ]
